name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    strategy:
      matrix:
        dotnet: ['2.2.103', '3.0.100-preview8-013656']
    
    name: dotnet ${{ matrix.dotnet }}
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - run: dotnet build
    
    - name: Run tests
    - run: dotnet test
    
